Load_Scheduler/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path
from Runs import views
from django.conf.urls.static import static
from django.conf import settings



urlpatterns = [
    path('admin/', admin.site.urls),
    
    #Auth Codes
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    #Runs
    path('schedule/create', views.create_run.as_view(), name='create_run' ),
    path('runs/', views.detail_run.as_view(), name='detail_run' ),
    path('schedule/<int:pk>/update', views.update_run.as_view(), name='update_run' ),
    path('schedule/<int:pk>/delete', views.delete_run.as_view(), name='delete_run' ),
    path('schedule/<int:pk>/pdf', views.GeneratePdf.as_view(), name='GeneratePdf' ),
    path('', views.Table_View.as_view(), name='Table_View'),
    path('schedule/detailspdf/', views.detailspdf.as_view(),name='detailspdf'),
    #path('schedule/csv', views.export_view.as_view(), name='export_view')
    
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Runs/models.py
from django.db import models
from django.contrib.auth.models import User

import pandas as pd
from django.conf import settings
from django_pandas.io import read_frame

class staffname(models.Model):
    fullname=models.CharField(max_length=50)
    objects = models.Manager()

    def __str__(self):
        return self.fullname


class Permit(models.Model):
        Truck =models.CharField(max_length=50)
        TBC=models.CharField(max_length=50)
        H180J=models.CharField(max_length=10)
        FC505=models.CharField(max_length=10)
        FC503=models.CharField(max_length=10)
        FC504=models.CharField(max_length=10)
        M441R=models.CharField(max_length=10)
        Q738U=models.CharField(max_length=10)
        BC606=models.CharField(max_length=10)
        BC606B=models.CharField(max_length=10)
        BC604=models.CharField(max_length=10)
        BC604B=models.CharField(max_length=10)
        BC605=models.CharField(max_length=10)
        BC605B=models.CharField(max_length=10)
        BC607=models.CharField(max_length=10)
        BC607B=models.CharField(max_length=10)
        BC608=models.CharField(max_length=10)
        BC608B=models.CharField(max_length=10)
        BC602=models.CharField(max_length=10)
        BC602B=models.CharField(max_length=10)
        BC619=models.CharField(max_length=10)
        BC619B=models.CharField(max_length=10)
        BC603=models.CharField(max_length=10)
        BC603B=models.CharField(max_length=10)
        BC615=models.CharField(max_length=10)
        BC615B=models.CharField(max_length=10)
        BC620=models.CharField(max_length=10)
        BC620B=models.CharField(max_length=10)
        BC609=models.CharField(max_length=10)
        BC609B=models.CharField(max_length=10)
        FC502=models.CharField(max_length=10)
        FC501=models.CharField(max_length=10)
        BC614=models.CharField(max_length=10)
        BC614B=models.CharField(max_length=10)
        BC621=models.CharField(max_length=10)
        BC621B=models.CharField(max_length=10)
        BC610=models.CharField(max_length=10)
        BC610B = models.CharField(max_length=10)
        BC622=models.CharField(max_length=10)
        BC622B=models.CharField(max_length=10)
        BC623=models.CharField(max_length=10)
        BC623B=models.CharField(max_length=10)
        BC510=models.CharField(max_length=10, default='No')
        A125=models.CharField(max_length=10, default='No')
        A125B=models.CharField(max_length=10, default='No')
        ASJ583=models.CharField(max_length=10, default='No')
        AZP219=models.CharField(max_length=10, default='No')
        B373J=models.CharField(max_length=10, default='No')
        BC503=models.CharField(max_length=10, default='No')
        BC503B=models.CharField(max_length=10, default='No')
        BC506=models.CharField(max_length=10, default='No')
        BC506B=models.CharField(max_length=10, default='No')
        BC507=models.CharField(max_length=10, default='No')
        BC507B=models.CharField(max_length=10, default='No')
        BC509=models.CharField(max_length=10, default='No')
        BC509B=models.CharField(max_length=10, default='No')
        BC510B=models.CharField(max_length=10, default='No')
        BC511=models.CharField(max_length=10, default='No')
        BC511B=models.CharField(max_length=10, default='No')
        BC513B=models.CharField(max_length=10, default='No')
        BC514B=models.CharField(max_length=10, default='No')
        BC516=models.CharField(max_length=10, default='No')
        BC516B=models.CharField(max_length=10, default='No')
        BC518=models.CharField(max_length=10, default='No')
        BC518B=models.CharField(max_length=10, default='No')
        BC519B=models.CharField(max_length=10, default='No')
        BC520B=models.CharField(max_length=10, default='No')
        BC601=models.CharField(max_length=10, default='No')
        BC601B=models.CharField(max_length=10, default='No')
        BCF001=models.CharField(max_length=10, default='No')
        BCF002=models.CharField(max_length=10, default='No')
        BCF002B=models.CharField(max_length=10, default='No')
        BCF004=models.CharField(max_length=10, default='No')
        BCF005=models.CharField(max_length=10, default='No')
        BCF005B=models.CharField(max_length=10, default='No')
        FC401=models.CharField(max_length=10, default='No')
        FC402=models.CharField(max_length=10, default='No')
        FC403=models.CharField(max_length=10, default='No')
        FC404=models.CharField(max_length=10, default='No')
        FC408=models.CharField(max_length=10, default='No')
        FC409=models.CharField(max_length=10, default='No')
        CS403=models.CharField(max_length=10, default='No')
        SC403=models.CharField(max_length=10, default='No')
        U2982=models.CharField(max_length=10, default='No')
        Ole_Blue=models.CharField(max_length=10, default='No')
        GMU582=models.CharField(max_length=10, default='No')
        ST50_REAR=models.CharField(max_length=10, default='No')
        W469D=models.CharField(max_length=10, default='No')
        SW304=models.CharField(max_length=10, default='No')
        BCF003=models.CharField(max_length=10, default='No')
        SC301=models.CharField(max_length=10, default='No')
        ST50_Front=models.CharField(max_length=10, default='No')
        MT4028=models.CharField(max_length=10, default='No')
        P839B=models.CharField(max_length=10, default='No')
        SK401=models.CharField(max_length=10, default='No')
        DJC531=models.CharField(max_length=10, default='No')
        NI4214=models.CharField(max_length=10, default='No')
        GQS618=models.CharField(max_length=10, default='No')
        DYS67=models.CharField(max_length=10, default='No')
        ST72_Rear=models.CharField(max_length=10, default='No')
        S2632=models.CharField(max_length=10, default='No')
        FD402=models.CharField(max_length=10, default='No')
        ZK7820=models.CharField(max_length=10, default='No')
        BC508=models.CharField(max_length=10, default='No')
        SW302=models.CharField(max_length=10, default='No')
        SW401=models.CharField(max_length=10, default='No')
        BC508B=models.CharField(max_length=10, default='No')
        Ole_Yellow=models.CharField(max_length=10, default='No')
        Q602A_Rear=models.CharField(max_length=10, default='No')
        S2631=models.CharField(max_length=10, default='No')
        RH3415=models.CharField(max_length=10, default='No')
        SC402=models.CharField(max_length=10, default='No')
        N771A=models.CharField(max_length=10, default='No')
        ST61_Rear=models.CharField(max_length=10, default='No')
        FUM497=models.CharField(max_length=10, default='No')
        BC603=models.CharField(max_length=10, default='No')
        SK306=models.CharField(max_length=10, default='No')
        SW301=models.CharField(max_length=10, default='No')
        FD401=models.CharField(max_length=10, default='No')
        Ole_Blue=models.CharField(max_length=10, default='No')
        SK402=models.CharField(max_length=10, default='No')
        SR401=models.CharField(max_length=10, default='No')
        R705S=models.CharField(max_length=10, default='No')
        M339B=models.CharField(max_length=10, default='No')
        EWM744=models.CharField(max_length=10, default='No')
        N8017=models.CharField(max_length=10, default='No')
        SK304=models.CharField(max_length=10, default='No')
        M928M=models.CharField(max_length=10, default='No')
        SK303=models.CharField(max_length=10, default='No')
        Ole_Yellow=models.CharField(max_length=10, default='No')


       
        

        objects = models.Manager()

        def __str__(self):
            return self.Truck

        
#Permit convert to DF and truck list
qs = Permit.objects.all()
df = read_frame(qs).set_index('Truck')
df2 = read_frame(qs)
trucklist= list(df2.Truck)
trucklistsorted = sorted(trucklist)
newlis = [(x , x) for x in trucklistsorted]

staff = staffname.objects.all()
staffdf = read_frame(staff)
stafflist = list(staffdf.fullname)
staffsort = sorted(stafflist)
stafflisttuples = [(x , x) for x in staffsort]


class routes(models.Model):
    route = models.CharField(max_length=6)
    objects = models.Manager()

    def __str__(self):
        return self.route


root = routes.objects.all()
routedf = read_frame(root)
routelist = list(routedf.route)
routelistsort = sorted(routelist)
routelisttuples = [(x , x) for x in routelistsort]


class front_trailer(models.Model):
    ftrailer = models.CharField(max_length=12)
    objects = models.Manager()

    def __str__(self):
        return self.ftrailer

ft = front_trailer.objects.all()
ftdf = read_frame(ft)
ftlist = list(ftdf.ftrailer)
ftlistsort = sorted(ftlist)
ftlisttuples = [(x , x) for x in ftlistsort]

class back_trailer(models.Model):
    btrailer = models.CharField(max_length=12)
    objects = models.Manager()

    def __str__(self):
        return self.btrailer

bt = back_trailer.objects.all()
btdf = read_frame(bt)
btlist = list(btdf.btrailer)
btlistsort = sorted(btlist)
btlisttuples = [(x , x) for x in btlistsort]


class Runs(models.Model):
    
    run = models.CharField(choices=routelisttuples, max_length=10)
    driver = models.CharField(choices=stafflisttuples,max_length=50,null=True, blank=True)
    truck = models.CharField(choices=newlis,max_length=50)
    trailer_1 = models.CharField(choices=ftlisttuples,max_length=50)
    trailer_2 = models.CharField(choices=btlisttuples, max_length=50, null=True, blank=True)
    load_comments = models.CharField(max_length=255,null=True, blank=True)
    return_load_comments = models.CharField(max_length=255, null=True, blank=True)
    depart_date = models.DateField()
    depart_time = models.TimeField(null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    objects = models.Manager()
    Planned_depart_time = models.TimeField()

Runs/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, UpdateView, DeleteView, View
from django.contrib.auth.forms import UserCreationForm
from .models import Runs
from django.contrib.auth import authenticate, login
from .filters import filter_runs
from .permit import permit_call
from django.utils import timezone
from .utils import render_to_pdf
from django.http import HttpResponse
from django_tables2 import SingleTableView
from .tables import RunTable
from django_filters.views import FilterView
from django_tables2.views import SingleTableMixin
from django.views.generic.dates import DayArchiveView
from django_tables2.export.views import ExportMixin




def home(request):
    return render(request, 'Runs/home.html')


class SignUp(CreateView):
    form_class= UserCreationForm
    success_url=reverse_lazy('Table_View')
    template_name ='registration/signup.html'

    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class create_run(CreateView):
    model = Runs
    fields = ['run','driver', 'truck','trailer_1', 'trailer_2', 'load_comments', 'return_load_comments','depart_date','depart_time','Planned_depart_time','foodstuffs', 'gib', 'run_details','weight', 'cubic']
    template_name = 'Runs/create_run.html'
    success_url =   reverse_lazy('Table_View')

    def form_valid(self, form):
        form.instance.user = self.request.user
        super(create_run, self).form_valid(form)
        return redirect('Table_View')


class Table_View(ExportMixin, SingleTableMixin,FilterView ):
    model = Runs
    table_class = RunTable
    template_name = 'Runs/table.html'
    filterset_class = filter_runs
    
    

    def get_filterset_kwargs(self,*args):
        kwargs = super().get_filterset_kwargs(*args)
        if kwargs['data']:
            bucket_filter_data = kwargs['data']
            self.request.session['bucket_filter_data']= bucket_filter_data
        else:
            if 'bucket_filter_data' in self.request.session.keys():
                kwargs['data']=self.request.session['bucket_filter_data']
        return kwargs

    

class detail_run(ListView):
    model = Runs
    runset = Runs.objects.all()
    template_name ='Runs/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = filter_runs(self.request.GET, queryset=self.get_queryset())
        return context
        

class update_run(UpdateView):
    model = Runs
    template_name ='Runs/update.html' 
    fields = ['run','driver', 'truck','trailer_1', 'trailer_2', 'load_comments', 'return_load_comments','depart_date','depart_time','Planned_depart_time','finished_loading_time','foodstuffs', 'gib','run_details','weight', 'cubic']
    success_url =   reverse_lazy('Table_View')

    
class delete_run(DeleteView):
    model = Runs
    template_name ='Runs/delete.html' 
    success_url =   reverse_lazy('Table_View')


class GeneratePdf(DetailView):
    model = Runs
    
   
    def get(self, request, pk, *args, **kwargs):
        runset = Runs.objects.get(pk=self.kwargs.get('pk'))
        data = {
             'runset': runset, 
        }
        pdf = render_to_pdf('Runs/pdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')


class detailspdf(DetailView):
    model = Runs
    success_url =   reverse_lazy('Table_View')
    


    def get(self, request, plan_date, *args, **kwargs):
        
        detailset = Runs.objects.filter(planning_date = plan_date)
        data = {
            'detailset': detailset, 
        }
        pdf = render_to_pdf('Runs/detailspdf.html', data)
        return HttpResponse(pdf, content_type='application/pdf')

       

""" class export_view(SingleTableView, ExportMixin, FilterView ):
    model = Runs
    table_class = RunTable
    template_name = 'Runs/table.html'
    filterset_class = filter_runs
    export_formats = ['csv', 'xlsx'] """
 
    

Runs/templates/Runs/base.html
<!doctype html>
<html lang="en">
{% load static %}


<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Summerland Express Freight</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
  <link href="{% static 'custom.css' %}" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{% static 'myfavicon.ico' %}" />
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
  <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-dark border-bottom shadow-sm">
    <h3 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'Table_View' %}" class="text-light">Summerland Express Freight - Day Planner</a></h3>
    <h6 class="p-3 text-light">User Name: {{ user }}</h6> 
    <nav class="my-2 my-md-0 mr-md-3">
      {% if user.is_authenticated %}    
      <a class="btn btn-primary p-2 text-light" href="{% url 'create_run' %}">Create Run</a>
      <a class="btn btn-primary p-2 text-light" href="{% url 'logout' %}">Log Out</a>
      
    
      {% else %}
      <a class="btn btn-primary p-2 text-light" href="{% url 'login' %}">Log In</a>
      {% endif %}
    </nav>
    {% if user.is_authenticated == False %}
    <a class="btn btn-primary p-2 text-light" href="{% url 'signup' %}">Sign up</a>
    {% endif %}
  </div>

  {% block content %}
  {% endblock %}


  <footer class="pageFooter sticky-bottom">

    <p class="text-center">© Summerland Express Freight 2020</p>
  
  </footer>

 
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
  <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />

  <script>
    $('#departdate').datepicker({
      uiLibrary: 'bootstrap4',format: 'yyyy-mm-dd'
    });
  </script>
  <script>
    $('#departtime').timepicker({
      uiLibrary: 'bootstrap4'
    });
  </script>
  <script>
    $('#departtime2').timepicker({
      uiLibrary: 'bootstrap4',
      });
  </script>
  <script>
  $('#plan_date').datepicker({
      uiLibrary: 'bootstrap4', format: 'yyyy-mm-dd'
      })
  </script>
  <script>
    $('#id_depart_date').datepicker({
      uiLibrary: 'bootstrap4', format: 'yyyy-mm-dd'
      })
  </script>
  <script>
    $('#id_Planned_depart_time').timepicker({
      uiLibrary: 'bootstrap4',
      });
  </script>
  <script>
    $(document).ready(function() {
    $("#btnFetch").click(function() {
    // disable button
    $(this).prop("disabled", false);
    // add spinner to button
    $(this).html(
    '<i class="fa fa-circle-o-notch fa-spin"></i> loading...'
    );
    });
    });
  </script>


</body>





</html>

Runs/templates/Runs/create_run.html
{% extends 'Runs/base.html' %}

{% load crispy_forms_tags %}

{% block content %}

<h1 class="d-flex justify-content-center row-hl p-3">Create Run</h1>
<div class="d-flex justify-content-center row-h1 p-3">
  
<form action="" method="post">
{% csrf_token %}

<div class="row form-group alert alert-primary">
  <div class="col-3">
    <h6>Planned Depart Date</h6>
      <input id='departdate' name='depart_date' placeholder="Depart Date"></input>
    </div>
    <div class="col-3">
      <h6>Planned Depart Time</h6>
      <input id='departtime2' name='Planned_depart_time'placeholder="Planned Depart Time" ></input>
    </div>
    
      
</div>
<br>
<div class="row">
  <div class="col-12">
    {{ form.run_details|as_crispy_field }}
  </div>
</div> 
<br>
<div class="row  form-group alert alert-primary">
    <div class="col-2">
      {{ form.run|as_crispy_field }}
    </div>
    <div class="col-2">
      {{ form.driver|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.truck|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.trailer_1|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.trailer_2|as_crispy_field }}
    </div>
</div>

<div class="row">
  <div class="col-2">
    {{ form.foodstuffs|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.gib|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.weight|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.cubic|as_crispy_field }}
  </div>
</div>

<div class="row">
    <div class="col-12">
      {{ form.load_comments|as_crispy_field }}
    </div>
</div>

<div class="row">
    <div class="col-12">
      {{ form.return_load_comments|as_crispy_field }}
    </div>
</div>  
<br>

  <input type='submit' value="Create Run" class='btn btn-primary'>

</form>
</div>

{% endblock content %}

Runs/templates/Runs/delete.html
{% extends 'Runs/base.html' %}

{% load crispy_forms_tags %}

{% block content %}




<div class="container pt-3">
<form action="" method="post">
    <h1 class="p-3">Delete Run</h1>
    <h3>Are you sure you want to delete run: {{ object.run }} - {{ object.depart_date }}</h3>
    {% csrf_token %}

    

    <input type='submit' value="Confirm" class='btn btn-danger'>

</form>
</div>
{% endblock content %}

Runs/templates/Runs/detail.html
{% extends 'Runs/base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}

{% block content %}

<div class="container-fluid pt-3">

      <div class="d-flex flex-row bd-highlight mb-3">
        <form action="" method="get">
        {{filter.form}}
        <br>
        <button type="submit" class="btn btn-primary p-2">Search</button>
        </form>
      </div>       
    <br>
    <div class="table-responsive-lg">  
    <table class="table table-hover table-striped">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Depart Date</th>
            <th scope="col">Run</th>
            <th scope="col">Planned Depart Time</th>
            <th scope="col">Actual Depart Time</th>
            <th scope="col">Driver</th>
            <th scope="col">Truck</th>
            <th scope="col">Trailer 1</th>
            <th scope="col">Trailer 2</th>
            <th scope="col">Permitted</th>
            <th scope="col">Load Details</th>
            <th scope="col">Return Load</th>
            <th scope="col">Action</th>
          </tr>
        </thead>
        <tbody>
            {% for run in filter.qs %}            
          <tr>
            <td scope="row">{{ run.depart_date }}</td>
            <td>{{ run.run }}</td>
            <td>{{ run.Planned_depart_time }}</td>
            <td>{{ run.depart_time }}</td>
            <td>{{ run.driver }}</td>
            <td>{{ run.truck }}</td>
            <td>{{ run.trailer_1 }}</td>
            <td>{{ run.trailer_2 }}</td>
            <td>{{ run.permit_call }}</td>
            <td>{{ run.load_comments }}</td>
            <td>{{ run.return_load_comments }}</td>
            {% if user.is_authenticated %}
            <td>
              <div class="btn-group" role="group">
                <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Action</button>
                <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                  <a class="dropdown-item" href="{% url 'update_run' run.id %}">Update</a>
                  <a class="dropdown-item" href="{% url 'delete_run' run.id %}">Delete</a>
                  <a class="dropdown-item" href="{% url 'GeneratePdf' run.id %}">Print Run Detail</a>
                </div>
              </div>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
      </div>
</div>
{% endblock content %}

  

Runs/templates/Runs/home.html
{% extends 'Runs/base.html' %}


{% block content %}


<div class="container pt-5">This is the home page</div>


{% endblock content %}

Runs/templates/Runs/table.html
{% extends 'Runs/base.html' %}
{% load django_tables2 %}
{% load render_table from django_tables2 %}
{% load bootstrap4 %}
{% load export_url from django_tables2 %}
{% load i18n %}


{% block content %}
<br>
<br>
{% if user.is_authenticated == False %}
<h1 class="text-center">Please Log In</h1>
{% endif %}

<br>


{% if user.is_authenticated %}
<div class="container-fluid pt-3">



    


{% if filter %}
    <form action="" method="get" class="form form-inline">

        {% bootstrap_form filter.form layout='inline' %}
        {% bootstrap_button 'Search' %}
        <a class="btn btn-primary ml-1" href="{% export_url 'csv' %}">Export Runs</a>
    
        
    </form>
    
{% endif %}



<br>
 

{% render_table table 'django_tables2/bootstrap4.html' %}

<h5>Total Runs {{ table.rows|length }}</h5>

</div>
{% endif %}
<br>



{% endblock content %}

Runs/templates/Runs/update.html
{% extends 'Runs/base.html' %}

{% load crispy_forms_tags %}

{% block content %}



<h1 class="d-flex justify-content-center row-hl p-3">Update Run</h1>
<div class="d-flex justify-content-center row-hl p-3">

<form action="" method="post">
{% csrf_token %}


 



<div class="row">
  
    <div class="col-3">
      <div id="div_id_depart_time" class="form-group alert alert-danger">
          <label for="id_depart_time" class="">
               Actual Depart time
          </label>
          <div class="">
            <input type="text" name="depart_time" class="timeinput form-control" id="id_depart_time" placeholder="HH:MM">
           </div>
         </div>
        </div>
    <div class="col-3">
      <div id="div_id_finished_loading_time" class="form-group alert alert-danger">
          <label for="id_finished_loading_time" class="">
                Finish Loading time
          </label>
          <div class="">
            <input type="text" name="finished_loading_time" class="timeinput form-control" id="finished_loading_time" placeholder="HH:MM">
            </div>
          </div>
        </div>     
        
</div>


  <div class="row">
    <div class="col-2">
        {{ form.depart_date|as_crispy_field }}
    </div>
    <div class="col-3">
        {{ form.Planned_depart_time|as_crispy_field }}
    </div>
  </div>

  <div class="row">
    <div class="col-12">
      {{ form.run_details|as_crispy_field }}
    </div>
  </div> 
  <br>

<div class="row">
  

    <div class="col-2">
      {{ form.run|as_crispy_field }}
    </div>
    <div class="col-2">
      {{ form.driver|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.truck|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.trailer_1|as_crispy_field }}
    </div>
    <div class="col-2">
        {{ form.trailer_2|as_crispy_field }}
    </div>
</div>
<div class="row">
  <div class="col-2">
    {{ form.foodstuffs|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.gib|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.weight|as_crispy_field }}
  </div>
  <div class="col-2">
    {{ form.cubic|as_crispy_field }}
  </div>
</div>
<div class="row">
    <div class="col-12">
      {{ form.load_comments|as_crispy_field }}
    </div>
</div>
<div class="row">
    <div class="col-12">
      {{ form.return_load_comments|as_crispy_field }}
    </div>
</div>  
<br>


<button type="buttonload" id="btnFetch" class="spinner-button btn btn-primary mb-2">Save</button>


</form>

</div>

{% endblock content %}